# Generated by Django 5.1.4 on 2025-01-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrainType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="FixedPrice",
        ),
        migrations.DeleteModel(
            name="RiceOrder",
        ),
    ]
