# Generated by Django 5.1.4 on 2025-01-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders_app", "0002_graintype_delete_fixedprice_delete_riceorder"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="GrainType",
        ),
    ]
