# Generated by Django 5.1.4 on 2025-01-05 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders_app", "0003_grain_delete_graintype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grain",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="GrainPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "grain",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders_app.grain",
                    ),
                ),
            ],
        ),
    ]
