# Generated by Django 5.1.4 on 2025-01-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders_app", "0004_alter_grain_name_grainprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grainprice",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
