# Generated by Django 5.1.4 on 2025-01-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders_app", "0005_alter_grainprice_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
