# Generated by Django 5.1.4 on 2025-01-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders_app", "0007_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
