# Generated by Django 5.1.4 on 2025-01-06 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders_app", "0008_deliverylocation_delete_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("amount_kg", models.PositiveIntegerField()),
                (
                    "grain_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders_app.grain",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DeliveryLocation",
        ),
    ]
