# Generated by Django 5.1.4 on 2025-01-06 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders_app", "0009_order_delete_deliverylocation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="grain_type",
            new_name="grain",
        ),
        migrations.AlterField(
            model_name="order",
            name="amount_kg",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
