# Generated by Django 5.1.4 on 2025-01-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders_app", "0011_order_ref_id_order_status_alter_order_amount_kg"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Preferably a WhatsApp number", max_length=15
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=6
                    ),
                ),
                ("state_of_residence", models.CharField(max_length=100)),
            ],
        ),
    ]
