# Generated by Django 5.1.4 on 2025-01-08 05:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders_app", "0012_customers"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="expected_delivery_date",
            field=models.DateField(default="2025-01-15"),
        ),
        migrations.AddField(
            model_name="order",
            name="order_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="order",
            name="ref_id",
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
