# Generated by Django 5.1.4 on 2025-01-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders_app", "0013_order_expected_delivery_date_order_order_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="ref_id",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
