# Generated by Django 5.1.4 on 2025-01-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders_app", "0014_alter_order_ref_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.CharField(max_length=255)),
                ("representative", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("state", models.CharField(max_length=255)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("Nigeria", "Nigeria"),
                            ("Ghana", "Ghana"),
                            ("South Africa", "South Africa"),
                            ("Kenya", "Kenya"),
                            ("United States", "United States"),
                            ("United Kingdom", "United Kingdom"),
                            ("Others", "Others"),
                        ],
                        default="Nigeria",
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
