# Generated by Django 5.1.4 on 2025-01-08 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders_app", "0016_alter_client_country_alter_client_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("grain_purchase", "Grain Purchase"),
                            ("winnowing", "Winnowing"),
                            ("threshing", "Threshing"),
                            ("transport", "Transport"),
                            ("warehousing", "Warehousing"),
                        ],
                        max_length=20,
                    ),
                ),
                ("transaction_date", models.DateField()),
                (
                    "transacting_org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders_app.client",
                    ),
                ),
            ],
        ),
    ]
